### ISSUE TITLE
Drum Tracks --> too many channels exception

### ISSUE THREAD

**Issue by DigitallyRemastered** [tg44/MidiSplitter#2]
Perhaps the 10th channel can be deleted from the file automatically in the program given it makes most files incompatible with the software.

**Comment by tg44** [comment]
I know it. I'm worked this "program" about 3-8 hour so its code quality and useability are really low. Its possible that today I give you a gui and some more functionality. (I go eating and write u a script for mass runing too.)

**Comment by DigitallyRemastered** [comment]
:D yay

**Comment by Ultrawipf** [comment]
This is great. Your software is what i always searched. But at the moment i get almost always a too many channels exception.

**Comment by tg44** [comment]
OK. I will work on it if i have some freetime. The problem is that if im not in the campus, I'm working or sleeping, and I hate programming user interfaces. (Its a mass work compared to its functionality if u write the code :) )

I started to code a normal chord split insted of this onthefly spliting, and trying to separate the chords like a human want to do.

Pls be patient a bit. I started this small project becouse I dont find this kind of tool so I know its in short supply.

**Comment by Ultrawipf** [comment]
you can wait with the interface until the code works perfectly. it is not so important for me.
Maybe a function to fill into empty tracks and if it generates too many tracks it could split into different files.
Today i prepared a new song using your software. It really helps with the splitting and gave me some usable tracks to work with :+1:

**Comment by tg44** [comment]
I started the graphical interface, I made it for easy add future functionality. I starting now a preprocess function which will say you if something not good, and an interface where u can keep tracks and channels untouchable.

**Comment by tg44** [comment]
I ended with the UI for a while. Now you coud uncheck the ch10 in the file tab and then the ch10 will be go to the outfile unmodified. Nearly unmodified, cos its instrument and channel number will be modified... Its a minor bug, but I think if sb want a fast conwerter instead of clicking thought a music again he will deal with this.

Next features will be the general tab checkboxes for the batch convert use, and the chord splitting instead of the first come first serve. But its not come before the next weak. If u find bugs or issues pls report them.

**Comment by tg44** [comment]
I think its working too. There is a small issue with the channel renumbering, but it coud easily resolved by any midi editing program.
