### ISSUE TITLE
mid not converted too much chennel

### ISSUE THREAD

**Issue by AAllport** [tg44/MidiSplitter#9]
what exactly does this mean and how do i fix it

**Comment by tg44** [comment]
When your midi has too much chennel, and you want to monophonic these channels, you coud run out the midi standard with the channel/track numbers.

The easyest way to resolve that is not converting all of your channels/tracks.

**Comment by DigitallyRemastered** [comment]
Hey tg44! Long time, no talk!

I thought of a better way to resolve this problem just now. Instead of writing notes to different channels, could you write them to different tracks?

For example, look at the midi editing software I use.
![example](https://cloud.githubusercontent.com/assets/1680276/7100093/9bb8f574-dfda-11e4-8c2b-b9b61e3c72ca.PNG)

Imagine that this image is of a midi taken after it was processed by your software. The midi that you fed to the program started out with 4 channels. After processing, it still has 4 channels, but it has several tracks.

The benefit is that a midi can have more than 16 tracks. The user can then listen to each track separately and see if a track is worth keeping. In my example, perhaps track 6 can be deleted. The user could then decide which tracks go to which channels.

Can ya help me out with this?

**Comment by DigitallyRemastered** [comment]
Actually, it would make more sense to get rid of Track 11. You know what I mean...

**Comment by tg44** [comment]
I see your point.
The channels are instruments. The tracks are seems to be tunes instead. So it seemed to be more logical to split a song into different "out devices" then different "logical devices".

More about the topic: http://www.homerecordinghub.com/midi-channels.html

I will take a look into this, I have a new aproach after I read your req.

**Comment by tg44** [comment]
Hmmm I looked in the code... Its need a bigger refactor if I want to implement this. The whole splitter is builded whit bool array for channels, now it must be added to every track separately. How to keep together the splits to the same tracks is a new question too.

So this is not a 30min problem. I have deadlines from the university too. I cant promise anything in this month.

**Comment by DigitallyRemastered** [comment]
Take your time, my friend. This revision is worth a decent wait.

**Comment by DigitallyRemastered** [comment]
Also, It would be nice if when one track is split into several tracks, you can tell where all the new tracks came from by their name. So for example:

Original Track Names:
Guitar
Bass
Trumpet

New Track Names
Guitar 1
Guitar 2
Guitar 3
Guitar 4
Bass 1
Trumpet 1
Trumpet 2
